episodes: 20

lr: 0.001
gamma: 0.99

# Episode/game limits (applied unless a game overrides)
steps_per_episode: 1800
goal_limit: 10

# Where to store RLlib checkpoints
output_dir: ./checkpoints
checkpoint_every: 10

# Optional initialization for Team A
init_teamA:
  load_ckpt: "checkpoints/teamA_ep20.pt"   # "" or omit to skip loading
  rand_std: 0.1                           # 0 or omit to skip random jitter
  include_core: false                      # false=jitter heads only; true=jitter encoder too
  teach:
    enabled: true                          # quick "move toward puck" warmup
    iters: 64
    lr: 0.001

# Optional initialization for Team B
init_teamB:
  load_ckpt: ""                            # "" or omit → no load
  rand_std: 0.02
  include_core: true
  teach:
    enabled: false


# Defaults applied to all games unless overridden below
defaults:
  num_agents_team_a: 3
  num_agents_team_b: 2
  team_a: neural    # options in this template: neural | simple
  team_b: simple
  rules:
    width: 800
    height: 600
    puck_radius: 12
    paddle_radius: 20
    friction_per_tick: 0.995
    puck_max_speed: 8.0
  rewards:
    score_delta: 1.0
    dist_to_puck_penalty: 0.001

# Optional: list of games to cycle through. If omitted, a single 'default' game is used.
# games:
#   - name: small_table_selfplay
#     num_agents_team_a: 1
#     num_agents_team_b: 1
#     team_a: neural
#     team_b: neural
#     rules:
#       width: 600
#       height: 400
#     rewards:
#       score_delta: 1.0
#       dist_to_puck_penalty: 0.0
