# Continuation Training Configuration
# Use this to continue training from a curriculum checkpoint

shared:
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  vf_coef: 0.5
  max_grad_norm: 0.5
  num_agents_team_a: 2
  num_agents_team_b: 2
  device: "cpu"
  hidden_dim: 128
  log_interval: 10
  save_interval: 50
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

# Single continuation phase - adjust parameters as needed
phase_1:
  name: "continued_training"
  timesteps: 500000  # 500K more timesteps
  opponent_type: "random"  # or "mixed" for variety
  learning_rate: 0.00005  # Lower LR for fine-tuning
  ent_coef: 0.01  # Lower entropy for exploitation
  clip_range: 0.2
  max_score: 3
  max_steps: 1200
  rewards:
    approach_puck_in_half: 0.2
    close_to_puck: 0.3
    puck_velocity_toward_goal: 1.5  # Emphasize scoring
    defensive_position: 0.2
    center_coverage: 0.2
    action_penalty: 0.001
    unnecessary_movement: 0.01
    teammate_collision: 0.5
